server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # مهم: Railway backend URL
    location /api/ {
        proxy_pass https://backend-production-d1ca.up.railway.app/api/;
    }

    location /auth/ {
        proxy_pass https://backend-production-d1ca.up.railway.app/auth/;
    }
}
